# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/series_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeriesWindow(object):
    def setupUi(self, SeriesWindow):
        SeriesWindow.setObjectName("SeriesWindow")
        SeriesWindow.resize(754, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(SeriesWindow)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(SeriesWindow)
        QtCore.QMetaObject.connectSlotsByName(SeriesWindow)

    def retranslateUi(self, SeriesWindow):
        _translate = QtCore.QCoreApplication.translate
        SeriesWindow.setWindowTitle(_translate("SeriesWindow", "Form"))
