# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/update_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updateDialog(object):
    def setupUi(self, updateDialog):
        updateDialog.setObjectName("updateDialog")
        updateDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        updateDialog.resize(726, 95)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(updateDialog.sizePolicy().hasHeightForWidth())
        updateDialog.setSizePolicy(sizePolicy)
        updateDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        updateDialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(updateDialog)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.updatesLabel = QtWidgets.QLabel(updateDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatesLabel.sizePolicy().hasHeightForWidth())
        self.updatesLabel.setSizePolicy(sizePolicy)
        self.updatesLabel.setObjectName("updatesLabel")
        self.horizontalLayout_5.addWidget(self.updatesLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.updatePercentLcdNumber = QtWidgets.QLCDNumber(updateDialog)
        self.updatePercentLcdNumber.setStyleSheet("")
        self.updatePercentLcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.updatePercentLcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.updatePercentLcdNumber.setMidLineWidth(0)
        self.updatePercentLcdNumber.setSmallDecimalPoint(True)
        self.updatePercentLcdNumber.setDigitCount(3)
        self.updatePercentLcdNumber.setObjectName("updatePercentLcdNumber")
        self.horizontalLayout_5.addWidget(self.updatePercentLcdNumber)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateProgressBar = QtWidgets.QProgressBar(updateDialog)
        self.updateProgressBar.setMaximum(1000)
        self.updateProgressBar.setProperty("value", 0)
        self.updateProgressBar.setObjectName("updateProgressBar")
        self.horizontalLayout_2.addWidget(self.updateProgressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.statusLabel = QtWidgets.QLabel(updateDialog)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.updateButton = QtWidgets.QPushButton(updateDialog)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout_2.addWidget(self.updateButton)
        self.discardButton = QtWidgets.QPushButton(updateDialog)
        self.discardButton.setObjectName("discardButton")
        self.verticalLayout_2.addWidget(self.discardButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(updateDialog)
        QtCore.QMetaObject.connectSlotsByName(updateDialog)

    def retranslateUi(self, updateDialog):
        _translate = QtCore.QCoreApplication.translate
        updateDialog.setWindowTitle(_translate("updateDialog", "Updates"))
        self.updatesLabel.setText(_translate("updateDialog", "Updates are avalible ..."))
        self.updateButton.setText(_translate("updateDialog", "Update"))
        self.discardButton.setText(_translate("updateDialog", "Discard"))
